const {chromium}=require(process.env.SM_PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve('crates/sm-server/src/web');
const ago=n=>new Date(Date.now()-n*60000).toISOString();
const ticket=(number,state='ready')=>({repo:'acme/widgets',number,title:`Ticket ${number}: preserve operational visibility`,state,warnings:[],waits_on:[],prs:[],jobs:[],docs:[]});
const rows=[ticket(1,'blocked'),ticket(2),ticket(3,'blocked'),ticket(4,'in_progress')];
rows[3].holder={session_id:'agent-4',name:'sm-1949-engineer',state:'working',provider:'codex-fork',since:ago(3)};
rows[3].jobs=[{id:'job-1',label:'Required repository checks',state:'running',since:ago(8),quiet_since:ago(2)},{id:'job-2',label:'Browser verification',state:'pending',since:ago(5)}];
rows[3].reviews=[{id:'review1',by:'agent',number:1950,reviewer_label:'Codex review',since:ago(10)},{id:'owner1',by:'you',number:1950,reviewer_label:'Rajesh review',since:ago(12)}];
rows[2].waits_on=[rows[1]];
const board={generated_at:new Date().toISOString(),lanes:[{id:1,rank:1,goal:rows[0],tickets:rows,counts:{ready:1,blocked:2,in_progress:1,done:0}}],other:[],repos:[]};
const settings={new_agent:{provider:'claude',claude:{model:'opus',effort:'high'},codex:{model:'gpt-6-sol',effort:'medium'},agent_types:[]}};
const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/app.css"><script type="importmap">{"imports":{"preact":"/vendor/preact.module.js","preact/hooks":"/vendor/hooks.module.js","htm":"/vendor/htm.module.js"}}</script></head><body><div id="app"></div><script type="module">import{render,h}from'preact';import{BoardPage}from'/board.js';render(h(BoardPage),document.getElementById('app'));</script></body></html>`;
(async()=>{const browser=await chromium.launch({executablePath:process.env.SM_CHROME_PATH,headless:true});try{
const page=await browser.newPage();const errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('https://board.test/**',async route=>{const u=new URL(route.request().url()),p=u.pathname;if(p==='/')return route.fulfill({contentType:'text/html',body:html});if(p.startsWith('/client/')){let body={};if(p==='/client/board')body=board;else if(p==='/client/settings')body=settings;else if(p==='/client/board/badge')body={count:0};else if(p==='/client/board/launch-preview'){const req=route.request().postDataJSON();writes.push({path:p,body:req});body={token:'preview',eligible_count:2,excluded_count:0,ready_count:1,blocked_count:1,renew_failed_count:0,cancel_count:0,items:req.selection.map(t=>({...t,eligible:true,behavior:req.common.behavior,effective_config:{...req.common.config,brief:null}}))};}else if(p==='/client/board/launch-selection'){writes.push({path:p,body:route.request().postDataJSON()});body={preferences_count:2,authorized_count:0,cancelled_count:0};}else if(p==='/client/board/start-options')body={provider:'claude',model:'opus',reasoning_effort:'high',brief:'Work this ticket',name:'test-engineer'};return route.fulfill({json:body});}const f=path.join(root,p);if(fs.existsSync(f))return route.fulfill({contentType:p.endsWith('.css')?'text/css':'text/javascript',body:fs.readFileSync(f)});throw Error('Unexpected route '+p);});
await page.goto('https://board.test/');await page.locator('[data-ticket="acme/widgets#4"]').waitFor();
for(const theme of ['light','dark']) for(const width of [1440,768,390]){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);await page.setViewportSize({width,height:1000});await page.screenshot({path:`/tmp/1949-board-${theme}-${width}.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`Overflow at ${width}`);for(const label of ['Required repository checks','Browser verification','Codex review','Rajesh review'])assert(await page.getByText(label,{exact:false}).first().isVisible(),label);}
await page.setViewportSize({width:1440,height:1000});await page.getByRole('checkbox',{name:'Select acme/widgets#2',exact:true}).check();await page.getByRole('checkbox',{name:'Select acme/widgets#3',exact:true}).check();
await page.getByRole('button',{name:/Codex.*gpt-6-sol/}).first().click();await page.getByRole('heading',{name:'Shared launch setup',exact:true}).waitFor();await page.getByRole('button',{name:'Review selection',exact:true}).click();await page.getByRole('button',{name:'Save preferences',exact:true}).waitFor();await page.screenshot({path:'/tmp/1949-shared-launch.png',fullPage:true});assert.equal(writes.length,1);assert.equal(writes[0].body.common.config.model,'gpt-6-sol');assert.equal(writes[0].body.common.behavior,'keep');await page.getByRole('button',{name:'Save preferences',exact:true}).click();await page.getByRole('heading',{name:'Shared launch setup',exact:true}).waitFor({state:'hidden'});assert.equal(writes.length,2);assert.match(writes[1].body.request_id,/^[a-f0-9-]{36}$/);assert.deepEqual(errors,[]);console.log('Browser layout at 1440, 768, 390; concurrent waits; preset preview and explicit save: passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
